#!/usr/bin/env bash
# Refreshes docs/memory.md and docs/researcher.md with current project state.
# Called automatically after every git commit via the Claude Code PostToolUse hook.
# Run manually any time: bash scripts/update-memory.sh
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MEMORY_FILE="$PROJECT_ROOT/docs/memory.md"
RESEARCHER_FILE="$PROJECT_ROOT/docs/researcher.md"
ACTIVE_PLAN="$PROJECT_ROOT/docs/plans/active-plan.md"

cd "$PROJECT_ROOT"

# ─── Gather git state ────────────────────────────────────────────────────────
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
LAST_5_COMMITS=$(git log --oneline -5 2>/dev/null || echo "(no commits)")
LAST_MODIFIED=$(git diff --name-only HEAD~1 HEAD 2>/dev/null | head -20 || echo "(initial commit)")
TIMESTAMP=$(date -u "+%Y-%m-%dT%H:%M:%SZ")

CURRENT_MILESTONE="(none)"
if [[ -f "$ACTIVE_PLAN" ]]; then
  CURRENT_MILESTONE=$(grep -E "^## Milestone" "$ACTIVE_PLAN" | tail -1 || echo "(no milestones found)")
fi

# ─── Write memory.md ─────────────────────────────────────────────────────────
cat > "$MEMORY_FILE" << MEMORY
# Project Memory

> Auto-updated by \`scripts/update-memory.sh\` on every git commit.
> **Claude: read this file at the start of every session before doing anything else.**
> Then read \`docs/researcher.md\` and \`docs/plans/active-plan.md\`.

## Last Updated
$TIMESTAMP

## Current Branch
\`$CURRENT_BRANCH\`

## Recent Commits (last 5)
\`\`\`
$LAST_5_COMMITS
\`\`\`

## Active Plan Milestone Reference
Plan: \`docs/plans/active-plan.md\`
Current milestone: $CURRENT_MILESTONE

## Last Modified Files (previous commit)
\`\`\`
$LAST_MODIFIED
\`\`\`

## Quick Commands
\`\`\`bash
docker compose -f docker-compose.dev.yml up -d   # start dev postgres
npm run dev                                       # start api + web
npm run db:migrate -- --name <desc>               # create migration
npm run db:studio                                  # open Prisma Studio
npm test                                           # run all tests
bash scripts/deploy.sh                             # deploy to production
\`\`\`
MEMORY

# ─── Gather codebase inventory for researcher.md ─────────────────────────────
PRISMA_MODELS=$(grep -E "^model " prisma/schema.prisma 2>/dev/null | sed 's/model /- /' | sed 's/ {//' || echo "(none)")
API_ROUTES=$(find apps/api/src/routes -name "*.ts" 2>/dev/null | sort | sed 's|apps/api/src/routes/||' | sed 's|^|- |' || echo "(none)")
WEB_PAGES=$(find apps/web/src/pages -name "*.tsx" 2>/dev/null | sort | sed 's|apps/web/src/pages/||' | sed 's|^|- |' || echo "(none)")

# Extract nav items from Sidebar (these are the active tools)
SIDEBAR_ITEMS=$(grep -oE "label: \"[^\"]+\"" apps/web/src/components/layout/Sidebar.tsx 2>/dev/null | sed 's/label: //' | sed 's/^/- /' || echo "(none)")

# Extract key dependency versions
ROOT_DEPS=$(node -e "
const p = require('./package.json');
const d = {...(p.devDependencies||{})};
const keys = ['turbo','typescript','eslint','vitest'];
keys.forEach(k => { if(d[k]) console.log('- ' + k + ': ' + d[k]) });
" 2>/dev/null || echo "(unavailable)")

API_DEPS=$(node -e "
const p = require('./apps/api/package.json');
const d = {...(p.dependencies||{}), ...(p.devDependencies||{})};
const keys = ['fastify','@prisma/client','zod','tsx'];
keys.forEach(k => { if(d[k]) console.log('- ' + k + ': ' + d[k]) });
" 2>/dev/null || echo "(unavailable)")

WEB_DEPS=$(node -e "
const p = require('./apps/web/package.json');
const d = {...(p.dependencies||{})};
const keys = ['react','vite','tailwindcss','@tanstack/react-query'];
keys.forEach(k => { if(d[k]) console.log('- ' + k + ': ' + d[k]) });
" 2>/dev/null || echo "(unavailable)")

# ─── Write researcher.md ─────────────────────────────────────────────────────
cat > "$RESEARCHER_FILE" << RESEARCHER
# Codebase Researcher Index

> Auto-generated by \`scripts/update-memory.sh\` on every git commit.
> Do not edit the auto-generated sections manually — changes will be overwritten.
> To add persistent notes, edit the **Notes** section at the bottom.

## Last Updated
$TIMESTAMP

## Prisma Models
$PRISMA_MODELS

## API Route Files
\`apps/api/src/routes/\`
$API_ROUTES

## Frontend Pages
\`apps/web/src/pages/\`
$WEB_PAGES

## Active Tools (Sidebar Nav)
$SIDEBAR_ITEMS

## Key Dependency Versions

### Root tooling
$ROOT_DEPS

### API (apps/api)
$API_DEPS

### Web (apps/web)
$WEB_DEPS

## Environment Variables Required
See \`.env.example\` (root) and \`apps/api/.env.example\` for full list.
Key vars: DATABASE_URL, PORT, CORS_ORIGIN, NTFY_URL (optional), NTFY_TOPIC (optional)

## Repository Layout
\`\`\`
apps/api/src/          Fastify API (env.ts → app.ts → plugins/ → routes/)
apps/web/src/          React frontend (App.tsx → AppShell → pages/)
packages/types/src/    Shared TypeScript types (API contracts)
prisma/                Database schema + migrations
docker/                Dockerfiles + nginx config
docs/                  memory.md, researcher.md, plans/
scripts/               deploy.sh, backup-db.sh, update-memory.sh
.claude/               Claude Code settings + hooks
tests/api/             Fastify integration tests (fastify.inject())
\`\`\`

## Notes
<!-- Claude: maintain this section when making significant architectural decisions.
     Example: "Added soft-delete pattern to all models (2026-06-08)"
     Example: "Route validation uses inline Zod schemas, not shared schema files" -->

RESEARCHER

echo "docs/memory.md and docs/researcher.md updated at $TIMESTAMP"
